version: "3.8"

services:

  db:
    image: postgres:15
    container_name: esim_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: esim
    #ports:
    #  - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: esim_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata: